import {
  Department,
  Level,
  Course,
  Unit,
  Trainer,
  Student,
  AssessmentSeries,
  Registration,
  InstitutionConfig,
  User,
  InAppNotification,
  UnitCategoryItem,
} from '../types';

export const INITIAL_UNIT_CATEGORIES: UnitCategoryItem[] = [
  { id: 'cat-core', name: 'Core', code: 'CR', description: 'Core Competency Units of Learning', badgeColor: 'purple', defaultAmount: 2500 },
  { id: 'cat-common', name: 'Common', code: 'CC', description: 'Common Broad Vocational Competencies', badgeColor: 'blue', defaultAmount: 1800 },
  { id: 'cat-basic', name: 'Basic', code: 'BC', description: 'Basic Foundational Competencies', badgeColor: 'slate', defaultAmount: 1200 },
  { id: 'cat-elective', name: 'Elective', code: 'EL', description: 'Specialized Elective Competencies', badgeColor: 'emerald', defaultAmount: 2000 },
  { id: 'cat-practical', name: 'Practical', code: 'PR', description: 'Workshop & Laboratory Practical Competencies', badgeColor: 'amber', defaultAmount: 3000 },
];

export const INITIAL_INSTITUTION_CONFIG: InstitutionConfig = {
  institutionName: 'THE SHAMBERERE NATIONAL POLYTECHNIC',
  departmentName: 'DEPARTMENT OF COMPUTING AND INFORMATICS',
  formReference: 'TSNP/CI/URF/006',
  postalAddress: 'P.O. BOX 1316-50100, Kakamega',
  email: 'info@shambererenationalpoly.ac.ke',
  altEmail: 'shambereretti@yahoo.com',
  phone: '0739-922-223',
  website: 'www.shambererenationalpoly.ac.ke',
  hodDesignation: 'Head of Department - Computing & Informatics',
  defaultCurrency: 'KES',
  currentAcademicYear: '2026',
  autoRoutingEnabled: true,
  allowPartialApproval: false,
  maxUnitsPerRegistration: 10,
  requireSignatures: true,
  reassessmentFee: 2000,
};

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-ci',
    name: 'Department of Computing and Informatics',
    code: 'CI',
    hodName: 'Dr. Kennedy Musumba',
    hodDesignation: 'Head of Department',
    hodEmail: 'hod.computing@shambererenationalpoly.ac.ke',
  },
  {
    id: 'dept-eng',
    name: 'Department of Electrical & Electronic Engineering',
    code: 'EEE',
    hodName: 'Eng. Patrick Wekesa',
    hodDesignation: 'Head of Department',
    hodEmail: 'hod.electrical@shambererenationalpoly.ac.ke',
  },
  {
    id: 'dept-biz',
    name: 'Department of Business Studies',
    code: 'BS',
    hodName: 'Mrs. Judith Omwamba',
    hodDesignation: 'Head of Department',
    hodEmail: 'hod.business@shambererenationalpoly.ac.ke',
  },
];

export const INITIAL_LEVELS: Level[] = [
  { id: 'lvl-6', name: 'Level 6 (Diploma)', code: 'LEVEL 6', description: 'Diploma Qualification Framework' },
  { id: 'lvl-5', name: 'Level 5 (Certificate)', code: 'LEVEL 5', description: 'Craft Certificate Qualification' },
  { id: 'lvl-4', name: 'Level 4 (Artisan)', code: 'LEVEL 4', description: 'Artisan Vocational Qualification' },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-dict',
    code: 'DICT',
    name: 'Diploma in Information Communication Technology',
    departmentId: 'dept-ci',
    levelId: 'lvl-6',
    durationSemesters: 6,
  },
  {
    id: 'course-dcs',
    code: 'DCS',
    name: 'Diploma in Computer Science & Software Engineering',
    departmentId: 'dept-ci',
    levelId: 'lvl-6',
    durationSemesters: 6,
  },
  {
    id: 'course-cit',
    code: 'CIT',
    name: 'Certificate in Information Technology',
    departmentId: 'dept-ci',
    levelId: 'lvl-5',
    durationSemesters: 4,
  },
  {
    id: 'course-art',
    code: 'ACA',
    name: 'Artisan Certificate in Computer Applications',
    departmentId: 'dept-ci',
    levelId: 'lvl-4',
    durationSemesters: 2,
  },
];

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'tr-mike',
    userId: 'user-tr-mike',
    name: 'Mr. Mike Trainer',
    email: 'miketrainer051@gmail.com',
    staffNumber: 'TSNP/TR/051',
    departmentId: 'dept-ci',
    phone: '0700-051-051',
    specialization: 'Web Applications, Mobile Development & Cloud Solutions',
  },
  {
    id: 'tr-01',
    userId: 'user-tr-01',
    name: 'Mr. Moses Wanjala',
    email: 'm.wanjala@shambererenationalpoly.ac.ke',
    staffNumber: 'TSNP/TR/084',
    departmentId: 'dept-ci',
    phone: '0712-345-678',
    specialization: 'Computer Networks, Web Development & Hardware Maintenance',
  },
  {
    id: 'tr-02',
    userId: 'user-tr-02',
    name: 'Ms. Faith Chebet',
    email: 'f.chebet@shambererenationalpoly.ac.ke',
    staffNumber: 'TSNP/TR/112',
    departmentId: 'dept-ci',
    phone: '0723-456-789',
    specialization: 'Database Systems, OOP & Data Structures',
  },
  {
    id: 'tr-03',
    userId: 'user-tr-03',
    name: 'Mr. Geoffrey Omondi',
    email: 'g.omondi@shambererenationalpoly.ac.ke',
    staffNumber: 'TSNP/TR/095',
    departmentId: 'dept-ci',
    phone: '0734-567-890',
    specialization: 'Digital Literacy, Communication Skills & Entrepreneurship',
  },
  {
    id: 'tr-04',
    userId: 'user-tr-04',
    name: 'Mrs. Everline Makokha',
    email: 'e.makokha@shambererenationalpoly.ac.ke',
    staffNumber: 'TSNP/TR/130',
    departmentId: 'dept-ci',
    phone: '0745-678-901',
    specialization: 'System Analysis, Cybersecurity & Cloud Computing',
  },
];

export const INITIAL_UNITS: Unit[] = [
  {
    id: 'unit-01',
    unitCode: 'ICT/CU/IT/BC/01/6/A',
    unitName: 'Demonstrate Communication Skills',
    category: 'Basic',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 1200,
    defaultTrainerId: 'tr-03',
    description: 'Oral, written, non-verbal communication and reporting in ICT enterprise',
    status: 'ACTIVE',
  },
  {
    id: 'unit-02',
    unitCode: 'ICT/CU/IT/BC/02/6/A',
    unitName: 'Demonstrate Digital Literacy',
    category: 'Basic',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 1200,
    defaultTrainerId: 'tr-03',
    description: 'Operating systems, office suites, digital productivity tools and cloud storage',
    status: 'ACTIVE',
  },
  {
    id: 'unit-03',
    unitCode: 'ICT/CU/IT/BC/03/6/A',
    unitName: 'Demonstrate Entrepreneurship Skills',
    category: 'Basic',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 1200,
    defaultTrainerId: 'tr-03',
    description: 'Business opportunity identification, financial planning and venture management',
    status: 'ACTIVE',
  },
  {
    id: 'unit-04',
    unitCode: 'ICT/CU/IT/CC/01/6/A',
    unitName: 'Apply Computer Networks Concepts',
    category: 'Common',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 1800,
    defaultTrainerId: 'tr-01',
    description: 'LAN/WAN architecture, TCP/IP subnetting, cabling, switches and routers setup',
    status: 'ACTIVE',
  },
  {
    id: 'unit-05',
    unitCode: 'ICT/CU/IT/CC/02/6/A',
    unitName: 'Apply Database Management Systems',
    category: 'Common',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 1800,
    defaultTrainerId: 'tr-02',
    description: 'Relational database design, ER modeling, SQL querying and normalization',
    status: 'ACTIVE',
  },
  {
    id: 'unit-06',
    unitCode: 'ICT/CU/IT/CR/01/6/A',
    unitName: 'Develop Web Applications',
    category: 'Core',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 2500,
    defaultTrainerId: 'tr-mike',
    description: 'HTML5, CSS3, JavaScript, server-side frameworks and database integration',
    status: 'ACTIVE',
  },
  {
    id: 'unit-07',
    unitCode: 'ICT/CU/IT/CR/02/6/A',
    unitName: 'Develop Object Oriented Programs',
    category: 'Core',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 2500,
    defaultTrainerId: 'tr-02',
    description: 'Classes, encapsulation, inheritance, polymorphism, Java/C# applications',
    status: 'ACTIVE',
  },
  {
    id: 'unit-08',
    unitCode: 'ICT/CU/IT/CR/03/6/A',
    unitName: 'Perform System Analysis and Design',
    category: 'Core',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 2500,
    defaultTrainerId: 'tr-04',
    description: 'SDLC methodologies, UML modeling, requirements engineering and UI design',
    status: 'ACTIVE',
  },
  {
    id: 'unit-09',
    unitCode: 'ICT/CU/IT/CR/04/6/A',
    unitName: 'Install & Maintain Computer Hardware',
    category: 'Core',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    amountCharged: 2200,
    defaultTrainerId: 'tr-01',
    description: 'PC assembly, troubleshooting, BIOS setup, peripheral devices and preventative servicing',
    status: 'ACTIVE',
  },
  // Certificate Units
  {
    id: 'unit-cit-01',
    unitCode: 'ICT/CU/IT/BC/01/5/A',
    unitName: 'Demonstrate Communication Skills (Cert)',
    category: 'Basic',
    courseId: 'course-cit',
    levelId: 'lvl-5',
    amountCharged: 1000,
    defaultTrainerId: 'tr-03',
    status: 'ACTIVE',
  },
  {
    id: 'unit-cit-02',
    unitCode: 'ICT/CU/IT/CC/01/5/A',
    unitName: 'Computer Maintenance and Troubleshooting',
    category: 'Common',
    courseId: 'course-cit',
    levelId: 'lvl-5',
    amountCharged: 1500,
    defaultTrainerId: 'tr-01',
    status: 'ACTIVE',
  },
  {
    id: 'unit-cit-03',
    unitCode: 'ICT/CU/IT/CR/01/5/A',
    unitName: 'Computer Applications Support',
    category: 'Core',
    courseId: 'course-cit',
    levelId: 'lvl-5',
    amountCharged: 1800,
    defaultTrainerId: 'tr-02',
    status: 'ACTIVE',
  },
];

export const INITIAL_ASSESSMENT_SERIES: AssessmentSeries[] = [
  {
    id: 'series-2026-nov',
    name: 'NOVEMBER/DECEMBER 2026 SERIES',
    year: '2026',
    openingDate: '2026-08-01',
    closingDate: '2026-12-20',
    status: 'ACTIVE',
  },
  {
    id: 'series-2026-july',
    name: 'JULY/AUGUST 2026 SERIES',
    year: '2026',
    openingDate: '2026-05-01',
    closingDate: '2026-08-30',
    status: 'CLOSED',
  },
  {
    id: 'series-2027-march',
    name: 'MARCH/APRIL 2027 SERIES',
    year: '2027',
    openingDate: '2027-01-15',
    closingDate: '2027-04-10',
    status: 'UPCOMING',
  },
];

export const INITIAL_USERS: User[] = [
  // Student 1
  {
    id: 'user-stu-01',
    name: 'Emmanuel Barasa',
    email: 'e.barasa@students.shambererenationalpoly.ac.ke',
    phone: '0711-223-344',
    role: 'STUDENT',
    identifierNumber: 'TSNP/DICT/2024/0482',
    departmentId: 'dept-ci',
    title: 'Level 6 Student',
    password: 'student123',
  },
  // Student 2
  {
    id: 'user-stu-02',
    name: 'Mercy Nekesa',
    email: 'm.nekesa@students.shambererenationalpoly.ac.ke',
    phone: '0722-334-455',
    role: 'STUDENT',
    identifierNumber: 'TSNP/DICT/2024/0519',
    departmentId: 'dept-ci',
    title: 'Level 6 Student',
    password: 'student123',
  },
  // Student 3
  {
    id: 'user-stu-03',
    name: 'Brian Kipruto',
    email: 'b.kipruto@students.shambererenationalpoly.ac.ke',
    phone: '0733-445-566',
    role: 'STUDENT',
    identifierNumber: 'TSNP/CIT/2025/0114',
    departmentId: 'dept-ci',
    title: 'Level 5 Student',
    password: 'student123',
  },
  // Student 4 (Earlier Trainee Cohort - Cycle 1)
  {
    id: 'user-stu-04',
    name: 'Johnstone Makokha',
    email: 'j.makokha@students.shambererenationalpoly.ac.ke',
    phone: '0714-998-877',
    role: 'STUDENT',
    identifierNumber: 'TSNP/DICT/2023/0019',
    departmentId: 'dept-ci',
    title: 'Cycle 1 Trainee (Earlier Cohort)',
    password: 'student123',
  },
  // Student 5 (Earlier Trainee Cohort - Cycle 2)
  {
    id: 'user-stu-05',
    name: 'Grace Nyambura',
    email: 'g.nyambura@students.shambererenationalpoly.ac.ke',
    phone: '0725-112-233',
    role: 'STUDENT',
    identifierNumber: 'TSNP/CIT/2023/0045',
    departmentId: 'dept-ci',
    title: 'Cycle 2 Trainee (Earlier Cohort)',
    password: 'student123',
  },
  // Trainer: Mike Trainer (miketrainer051@gmail.com)
  {
    id: 'user-tr-mike',
    name: 'Mr. Mike Trainer',
    email: 'miketrainer051@gmail.com',
    phone: '0700-051-051',
    role: 'TRAINER',
    identifierNumber: 'TSNP/TR/051',
    departmentId: 'dept-ci',
    title: 'Trainer (Web Applications & Systems)',
    password: 'trainer123',
  },
  // Trainer 1: Moses Wanjala
  {
    id: 'user-tr-01',
    name: 'Mr. Moses Wanjala',
    email: 'm.wanjala@shambererenationalpoly.ac.ke',
    phone: '0712-345-678',
    role: 'TRAINER',
    identifierNumber: 'TSNP/TR/084',
    departmentId: 'dept-ci',
    title: 'Senior ICT Trainer',
    password: 'trainer123',
  },
  // Trainer 2: Faith Chebet
  {
    id: 'user-tr-02',
    name: 'Ms. Faith Chebet',
    email: 'f.chebet@shambererenationalpoly.ac.ke',
    phone: '0723-456-789',
    role: 'TRAINER',
    identifierNumber: 'TSNP/TR/112',
    departmentId: 'dept-ci',
    title: 'Trainer (Software & Databases)',
    password: 'trainer123',
  },
  // Trainer 3: Geoffrey Omondi
  {
    id: 'user-tr-03',
    name: 'Mr. Geoffrey Omondi',
    email: 'g.omondi@shambererenationalpoly.ac.ke',
    phone: '0734-567-890',
    role: 'TRAINER',
    identifierNumber: 'TSNP/TR/095',
    departmentId: 'dept-ci',
    title: 'Trainer (Basic & Digital Skills)',
    password: 'trainer123',
  },
  // Trainer 4: Everline Makokha
  {
    id: 'user-tr-04',
    name: 'Mrs. Everline Makokha',
    email: 'e.makokha@shambererenationalpoly.ac.ke',
    phone: '0745-678-901',
    role: 'TRAINER',
    identifierNumber: 'TSNP/TR/130',
    departmentId: 'dept-ci',
    title: 'Trainer (System Analysis)',
    password: 'trainer123',
  },
  // HOD: Dr. Kennedy Musumba
  {
    id: 'user-hod-01',
    name: 'Dr. Kennedy Musumba',
    email: 'hod.computing@shambererenationalpoly.ac.ke',
    phone: '0799-887-766',
    role: 'HOD',
    identifierNumber: 'TSNP/HOD/012',
    departmentId: 'dept-ci',
    title: 'Head of Department, Computing & Informatics',
    password: 'hod123',
  },
  // Examinations Officer: Beatrice Agutu
  {
    id: 'user-exam-01',
    name: 'Mrs. Beatrice Agutu',
    email: 'exams@shambererenationalpoly.ac.ke',
    phone: '0788-776-655',
    role: 'EXAM_OFFICER',
    identifierNumber: 'TSNP/EXAM/004',
    departmentId: 'dept-ci',
    title: 'Senior Examinations Officer',
    password: 'exam123',
  },
  // System Admin
  {
    id: 'user-adm-01',
    name: 'Eng. David Shikuku',
    email: 'admin.ict@shambererenationalpoly.ac.ke',
    phone: '0777-665-544',
    role: 'ADMIN',
    identifierNumber: 'TSNP/ADM/001',
    departmentId: 'dept-ci',
    title: 'Principal ICT Systems Administrator',
    password: 'admin123',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu-01',
    userId: 'user-stu-01',
    admissionNumber: 'TSNP/DICT/2024/0482',
    name: 'Emmanuel Barasa',
    email: 'e.barasa@students.shambererenationalpoly.ac.ke',
    phone: '0711-223-344',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    departmentId: 'dept-ci',
    nationalId: '38942150',
    currentModule: 2,
    status: 'ACTIVE',
  },
  {
    id: 'stu-02',
    userId: 'user-stu-02',
    admissionNumber: 'TSNP/DICT/2024/0519',
    name: 'Mercy Nekesa',
    email: 'm.nekesa@students.shambererenationalpoly.ac.ke',
    phone: '0722-334-455',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    departmentId: 'dept-ci',
    nationalId: '39218471',
    currentModule: 2,
    status: 'ACTIVE',
  },
  {
    id: 'stu-03',
    userId: 'user-stu-03',
    admissionNumber: 'TSNP/CIT/2025/0114',
    name: 'Brian Kipruto',
    email: 'b.kipruto@students.shambererenationalpoly.ac.ke',
    phone: '0733-445-566',
    courseId: 'course-cit',
    levelId: 'lvl-5',
    departmentId: 'dept-ci',
    nationalId: '40192834',
    currentModule: 1,
    status: 'ACTIVE',
  },
  {
    id: 'stu-04',
    userId: 'user-stu-04',
    admissionNumber: 'TSNP/DICT/2023/0019',
    name: 'Johnstone Makokha',
    email: 'j.makokha@students.shambererenationalpoly.ac.ke',
    phone: '0714-998-877',
    courseId: 'course-dict',
    levelId: 'lvl-6',
    departmentId: 'dept-ci',
    nationalId: '36881920',
    currentModule: 'Cycle 1',
    status: 'ACTIVE',
  },
  {
    id: 'stu-05',
    userId: 'user-stu-05',
    admissionNumber: 'TSNP/CIT/2023/0045',
    name: 'Grace Nyambura',
    email: 'g.nyambura@students.shambererenationalpoly.ac.ke',
    phone: '0725-112-233',
    courseId: 'course-cit',
    levelId: 'lvl-5',
    departmentId: 'dept-ci',
    nationalId: '37901824',
    currentModule: 'Cycle 2',
    status: 'ACTIVE',
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  // 1. Fully APPROVED Registration (Ready for Print / Download with Official Form matching TSNP/CI/URF/006)
  {
    id: 'reg-001',
    registrationReference: 'UR-2026-000142',
    studentId: 'stu-01',
    studentName: 'Emmanuel Barasa',
    admissionNumber: 'TSNP/DICT/2024/0482',
    courseId: 'course-dict',
    courseName: 'Diploma in Information Communication Technology',
    courseCode: 'DICT',
    levelId: 'lvl-6',
    levelName: 'LEVEL 6',
    departmentId: 'dept-ci',
    departmentName: 'DEPARTMENT OF COMPUTING AND INFORMATICS',
    assessmentSeriesId: 'series-2026-nov',
    assessmentSeriesName: 'NOVEMBER/DECEMBER 2026 SERIES',
    year: '2026',
    module: 2,
    totalAmount: 12900,
    status: 'APPROVED',
    submittedAt: '2026-06-10T09:30:00Z',
    lastUpdatedAt: '2026-06-12T14:45:00Z',
    units: [
      {
        id: 'ru-01',
        unitId: 'unit-01',
        unitCode: 'ICT/CU/IT/BC/01/6/A',
        unitName: 'Demonstrate Communication Skills',
        category: 'Basic',
        amountCharged: 1200,
        trainerId: 'tr-03',
        trainerName: 'Mr. Geoffrey Omondi',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T10:15:00Z',
        verifiedByTrainerName: 'Mr. Geoffrey Omondi',
        decisionComment: 'Satisfies class attendance and practical presentations requirement.',
        signatureRef: 'TSNP-VER-OMONDI-9021',
      },
      {
        id: 'ru-02',
        unitId: 'unit-02',
        unitCode: 'ICT/CU/IT/BC/02/6/A',
        unitName: 'Demonstrate Digital Literacy',
        category: 'Basic',
        amountCharged: 1200,
        trainerId: 'tr-03',
        trainerName: 'Mr. Geoffrey Omondi',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T10:18:00Z',
        verifiedByTrainerName: 'Mr. Geoffrey Omondi',
        decisionComment: 'Continuous assessment tests completed.',
        signatureRef: 'TSNP-VER-OMONDI-9022',
      },
      {
        id: 'ru-03',
        unitId: 'unit-03',
        unitCode: 'ICT/CU/IT/BC/03/6/A',
        unitName: 'Demonstrate Entrepreneurship Skills',
        category: 'Basic',
        amountCharged: 1200,
        trainerId: 'tr-03',
        trainerName: 'Mr. Geoffrey Omondi',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T10:20:00Z',
        verifiedByTrainerName: 'Mr. Geoffrey Omondi',
        decisionComment: 'Business plan proposal submitted.',
        signatureRef: 'TSNP-VER-OMONDI-9023',
      },
      {
        id: 'ru-04',
        unitId: 'unit-04',
        unitCode: 'ICT/CU/IT/CC/01/6/A',
        unitName: 'Apply Computer Networks Concepts',
        category: 'Common',
        amountCharged: 1800,
        trainerId: 'tr-01',
        trainerName: 'Mr. Moses Wanjala',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T11:45:00Z',
        verifiedByTrainerName: 'Mr. Moses Wanjala',
        decisionComment: 'Cisco Packet Tracer lab practicals verified.',
        signatureRef: 'TSNP-VER-WANJALA-4410',
      },
      {
        id: 'ru-05',
        unitId: 'unit-05',
        unitCode: 'ICT/CU/IT/CC/02/6/A',
        unitName: 'Apply Database Management Systems',
        category: 'Common',
        amountCharged: 1800,
        trainerId: 'tr-02',
        trainerName: 'Ms. Faith Chebet',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T14:30:00Z',
        verifiedByTrainerName: 'Ms. Faith Chebet',
        decisionComment: 'MySQL practical project cleared.',
        signatureRef: 'TSNP-VER-CHEBET-8812',
      },
      {
        id: 'ru-06',
        unitId: 'unit-06',
        unitCode: 'ICT/CU/IT/CR/01/6/A',
        unitName: 'Develop Web Applications',
        category: 'Core',
        amountCharged: 2500,
        trainerId: 'tr-01',
        trainerName: 'Mr. Moses Wanjala',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T11:50:00Z',
        verifiedByTrainerName: 'Mr. Moses Wanjala',
        decisionComment: 'Portfolio website and backend portal hosted and inspected.',
        signatureRef: 'TSNP-VER-WANJALA-4411',
      },
      {
        id: 'ru-07',
        unitId: 'unit-07',
        unitCode: 'ICT/CU/IT/CR/02/6/A',
        unitName: 'Develop Object Oriented Programs',
        category: 'Core',
        amountCharged: 2500,
        trainerId: 'tr-02',
        trainerName: 'Ms. Faith Chebet',
        status: 'APPROVED',
        verifiedAt: '2026-06-11T14:35:00Z',
        verifiedByTrainerName: 'Ms. Faith Chebet',
        decisionComment: 'Java OOP final coursework submitted.',
        signatureRef: 'TSNP-VER-CHEBET-8813',
      },
    ],
    hodApproval: {
      hodId: 'user-hod-01',
      hodName: 'Dr. Kennedy Musumba',
      designation: 'Head of Department, Computing & Informatics',
      decision: 'APPROVED',
      comments: 'All 7 CDACC Assessment Units verified by respective subject trainers. Candidate eligible for July/August 2026 Series.',
      approvedAt: '2026-06-12T14:45:00Z',
      approvalRef: 'TSNP/CI/APP/2026/0482',
    },
    resubmissionCount: 0,
    auditLogs: [
      {
        id: 'log-01',
        timestamp: '2026-06-10T09:30:00Z',
        userId: 'user-stu-01',
        userName: 'Emmanuel Barasa',
        userRole: 'STUDENT',
        action: 'SUBMIT_REGISTRATION',
        details: 'Submitted registration with 7 units for July/August 2026 Series.',
        previousStatus: 'DRAFT',
        newStatus: 'SUBMITTED',
      },
      {
        id: 'log-02',
        timestamp: '2026-06-11T10:20:00Z',
        userId: 'user-tr-03',
        userName: 'Mr. Geoffrey Omondi',
        userRole: 'TRAINER',
        action: 'VERIFY_UNITS',
        details: 'Approved units: BC/01, BC/02, BC/03.',
        previousStatus: 'SUBMITTED',
        newStatus: 'PARTIALLY_VERIFIED',
      },
      {
        id: 'log-03',
        timestamp: '2026-06-11T11:50:00Z',
        userId: 'user-tr-01',
        userName: 'Mr. Moses Wanjala',
        userRole: 'TRAINER',
        action: 'VERIFY_UNITS',
        details: 'Approved units: CC/01, CR/01.',
      },
      {
        id: 'log-04',
        timestamp: '2026-06-11T14:35:00Z',
        userId: 'user-tr-02',
        userName: 'Ms. Faith Chebet',
        userRole: 'TRAINER',
        action: 'VERIFY_UNITS',
        details: 'Approved units: CC/02, CR/02. All units verified.',
        previousStatus: 'PARTIALLY_VERIFIED',
        newStatus: 'AWAITING_HOD_APPROVAL',
      },
      {
        id: 'log-05',
        timestamp: '2026-06-12T14:45:00Z',
        userId: 'user-hod-01',
        userName: 'Dr. Kennedy Musumba',
        userRole: 'HOD',
        action: 'HOD_APPROVE',
        details: 'Granted departmental clearance and digital signature.',
        previousStatus: 'AWAITING_HOD_APPROVAL',
        newStatus: 'APPROVED',
      },
    ],
  },

  // 2. Multi-Trainer In-Progress (Mercy Nekesa: some verified, some pending)
  {
    id: 'reg-002',
    registrationReference: 'UR-2026-000143',
    studentId: 'stu-02',
    studentName: 'Mercy Nekesa',
    admissionNumber: 'TSNP/DICT/2024/0519',
    courseId: 'course-dict',
    courseName: 'Diploma in Information Communication Technology',
    courseCode: 'DICT',
    levelId: 'lvl-6',
    levelName: 'LEVEL 6',
    departmentId: 'dept-ci',
    departmentName: 'DEPARTMENT OF COMPUTING AND INFORMATICS',
    assessmentSeriesId: 'series-2026-nov',
    assessmentSeriesName: 'NOVEMBER/DECEMBER 2026 SERIES',
    year: '2026',
    totalAmount: 9800,
    status: 'PARTIALLY_VERIFIED',
    submittedAt: '2026-06-14T08:15:00Z',
    lastUpdatedAt: '2026-06-14T11:00:00Z',
    units: [
      {
        id: 'ru-11',
        unitId: 'unit-01',
        unitCode: 'ICT/CU/IT/BC/01/6/A',
        unitName: 'Demonstrate Communication Skills',
        category: 'Basic',
        amountCharged: 1200,
        trainerId: 'tr-03',
        trainerName: 'Mr. Geoffrey Omondi',
        status: 'APPROVED',
        verifiedAt: '2026-06-14T10:00:00Z',
        verifiedByTrainerName: 'Mr. Geoffrey Omondi',
        decisionComment: 'Eligible and completed communication portfolio.',
        signatureRef: 'TSNP-VER-OMONDI-9104',
      },
      {
        id: 'ru-12',
        unitId: 'unit-04',
        unitCode: 'ICT/CU/IT/CC/01/6/A',
        unitName: 'Apply Computer Networks Concepts',
        category: 'Common',
        amountCharged: 1800,
        trainerId: 'tr-01',
        trainerName: 'Mr. Moses Wanjala',
        status: 'PENDING',
      },
      {
        id: 'ru-13',
        unitId: 'unit-05',
        unitCode: 'ICT/CU/IT/CC/02/6/A',
        unitName: 'Apply Database Management Systems',
        category: 'Common',
        amountCharged: 1800,
        trainerId: 'tr-02',
        trainerName: 'Ms. Faith Chebet',
        status: 'PENDING',
      },
      {
        id: 'ru-14',
        unitId: 'unit-06',
        unitCode: 'ICT/CU/IT/CR/01/6/A',
        unitName: 'Develop Web Applications',
        category: 'Core',
        amountCharged: 2500,
        trainerId: 'tr-mike',
        trainerName: 'Mr. Mike Trainer',
        status: 'PENDING',
      },
      {
        id: 'ru-15',
        unitId: 'unit-07',
        unitCode: 'ICT/CU/IT/CR/02/6/A',
        unitName: 'Develop Object Oriented Programs',
        category: 'Core',
        amountCharged: 2500,
        trainerId: 'tr-02',
        trainerName: 'Ms. Faith Chebet',
        status: 'PENDING',
      },
    ],
    resubmissionCount: 0,
    auditLogs: [
      {
        id: 'log-11',
        timestamp: '2026-06-14T08:15:00Z',
        userId: 'user-stu-02',
        userName: 'Mercy Nekesa',
        userRole: 'STUDENT',
        action: 'SUBMIT_REGISTRATION',
        details: 'Submitted registration for 5 units in July/August 2026 Series.',
        previousStatus: 'DRAFT',
        newStatus: 'SUBMITTED',
      },
      {
        id: 'log-12',
        timestamp: '2026-06-14T10:00:00Z',
        userId: 'user-tr-03',
        userName: 'Mr. Geoffrey Omondi',
        userRole: 'TRAINER',
        action: 'VERIFY_UNITS',
        details: 'Approved unit BC/01.',
        previousStatus: 'SUBMITTED',
        newStatus: 'PARTIALLY_VERIFIED',
      },
    ],
  },

  // 3. Awaiting HOD Approval (Brian Kipruto - all 3 units verified by trainers)
  {
    id: 'reg-003',
    registrationReference: 'UR-2026-000144',
    studentId: 'stu-03',
    studentName: 'Brian Kipruto',
    admissionNumber: 'TSNP/CIT/2025/0114',
    courseId: 'course-cit',
    courseName: 'Certificate in Information Technology',
    courseCode: 'CIT',
    levelId: 'lvl-5',
    levelName: 'LEVEL 5',
    departmentId: 'dept-ci',
    departmentName: 'DEPARTMENT OF COMPUTING AND INFORMATICS',
    assessmentSeriesId: 'series-2026-nov',
    assessmentSeriesName: 'NOVEMBER/DECEMBER 2026 SERIES',
    year: '2026',
    totalAmount: 4300,
    status: 'AWAITING_HOD_APPROVAL',
    submittedAt: '2026-06-13T10:00:00Z',
    lastUpdatedAt: '2026-06-13T16:20:00Z',
    units: [
      {
        id: 'ru-21',
        unitId: 'unit-cit-01',
        unitCode: 'ICT/CU/IT/BC/01/5/A',
        unitName: 'Demonstrate Communication Skills (Cert)',
        category: 'Basic',
        amountCharged: 1000,
        trainerId: 'tr-03',
        trainerName: 'Mr. Geoffrey Omondi',
        status: 'APPROVED',
        verifiedAt: '2026-06-13T14:10:00Z',
        verifiedByTrainerName: 'Mr. Geoffrey Omondi',
        decisionComment: 'Passed coursework 1 and 2.',
        signatureRef: 'TSNP-VER-OMONDI-9090',
      },
      {
        id: 'ru-22',
        unitId: 'unit-cit-02',
        unitCode: 'ICT/CU/IT/CC/01/5/A',
        unitName: 'Computer Maintenance and Troubleshooting',
        category: 'Common',
        amountCharged: 1500,
        trainerId: 'tr-01',
        trainerName: 'Mr. Moses Wanjala',
        status: 'APPROVED',
        verifiedAt: '2026-06-13T15:30:00Z',
        verifiedByTrainerName: 'Mr. Moses Wanjala',
        decisionComment: 'Lab practicals and hardware teardown signed off.',
        signatureRef: 'TSNP-VER-WANJALA-4422',
      },
      {
        id: 'ru-23',
        unitId: 'unit-cit-03',
        unitCode: 'ICT/CU/IT/CR/01/5/A',
        unitName: 'Computer Applications Support',
        category: 'Core',
        amountCharged: 1800,
        trainerId: 'tr-02',
        trainerName: 'Ms. Faith Chebet',
        status: 'APPROVED',
        verifiedAt: '2026-06-13T16:20:00Z',
        verifiedByTrainerName: 'Ms. Faith Chebet',
        decisionComment: 'Applications project assessment cleared.',
        signatureRef: 'TSNP-VER-CHEBET-8840',
      },
    ],
    resubmissionCount: 0,
    auditLogs: [
      {
        id: 'log-21',
        timestamp: '2026-06-13T10:00:00Z',
        userId: 'user-stu-03',
        userName: 'Brian Kipruto',
        userRole: 'STUDENT',
        action: 'SUBMIT_REGISTRATION',
        details: 'Submitted 3 units registration.',
        previousStatus: 'DRAFT',
        newStatus: 'SUBMITTED',
      },
      {
        id: 'log-22',
        timestamp: '2026-06-13T16:20:00Z',
        userId: 'user-tr-02',
        userName: 'Ms. Faith Chebet',
        userRole: 'TRAINER',
        action: 'VERIFY_UNITS',
        details: 'All trainers completed verification. Registration routed to HOD approval queue.',
        previousStatus: 'PARTIALLY_VERIFIED',
        newStatus: 'AWAITING_HOD_APPROVAL',
      },
    ],
  },
  // 4. Cycle 1 Earlier Trainee Cohort Registration (Approved)
  {
    id: 'reg-004',
    registrationReference: 'UR-2026-000088',
    studentId: 'stu-04',
    studentName: 'Johnstone Makokha',
    admissionNumber: 'TSNP/DICT/2023/0019',
    courseId: 'course-dict',
    courseName: 'Diploma in Information Communication Technology',
    courseCode: 'DICT',
    levelId: 'lvl-6',
    levelName: 'LEVEL 6',
    departmentId: 'dept-ci',
    departmentName: 'DEPARTMENT OF COMPUTING AND INFORMATICS',
    assessmentSeriesId: 'series-2026-nov',
    assessmentSeriesName: 'NOVEMBER/DECEMBER 2026 SERIES',
    year: '2026',
    module: 'Cycle 1',
    totalAmount: 6500,
    status: 'APPROVED',
    submittedAt: '2026-06-08T08:30:00Z',
    lastUpdatedAt: '2026-06-09T15:10:00Z',
    units: [
      {
        id: 'ru-41',
        unitId: 'unit-01',
        unitCode: 'ICT/CU/IT/BC/01/6/A',
        unitName: 'Demonstrate Communication Skills',
        category: 'Basic',
        amountCharged: 1200,
        trainerId: 'tr-03',
        trainerName: 'Mr. Geoffrey Omondi',
        status: 'APPROVED',
        verifiedAt: '2026-06-08T11:00:00Z',
        verifiedByTrainerName: 'Mr. Geoffrey Omondi',
        decisionComment: 'Earlier cohort coursework validated.',
        signatureRef: 'TSNP-VER-OMONDI-8101',
      },
      {
        id: 'ru-42',
        unitId: 'unit-04',
        unitCode: 'ICT/CU/IT/CC/01/6/A',
        unitName: 'Apply Computer Networks Concepts',
        category: 'Common',
        amountCharged: 1800,
        trainerId: 'tr-01',
        trainerName: 'Mr. Moses Wanjala',
        status: 'APPROVED',
        verifiedAt: '2026-06-08T14:30:00Z',
        verifiedByTrainerName: 'Mr. Moses Wanjala',
        decisionComment: 'Network topology and lab practicals verified.',
        signatureRef: 'TSNP-VER-WANJALA-4401',
      },
      {
        id: 'ru-43',
        unitId: 'unit-06',
        unitCode: 'ICT/CU/IT/CR/01/6/A',
        unitName: 'Develop Web Applications',
        category: 'Core',
        amountCharged: 2500,
        trainerId: 'tr-01',
        trainerName: 'Mr. Moses Wanjala',
        status: 'APPROVED',
        verifiedAt: '2026-06-08T14:40:00Z',
        verifiedByTrainerName: 'Mr. Moses Wanjala',
        decisionComment: 'Web projects inspected.',
        signatureRef: 'TSNP-VER-WANJALA-4402',
      },
    ],
    hodApproval: {
      hodId: 'user-hod-01',
      hodName: 'Dr. Kennedy Musumba',
      designation: 'Head of Department, Computing & Informatics',
      decision: 'APPROVED',
      comments: 'Earlier trainee Cycle 1 candidate approved for assessment series.',
      approvedAt: '2026-06-09T15:10:00Z',
      approvalRef: 'TSNP-HOD-APP-2026-0044',
    },
    resubmissionCount: 0,
    auditLogs: [
      {
        id: 'log-41',
        timestamp: '2026-06-08T08:30:00Z',
        userId: 'user-stu-04',
        userName: 'Johnstone Makokha',
        userRole: 'STUDENT',
        action: 'SUBMIT_REGISTRATION',
        details: 'Submitted registration for Cycle 1 units.',
        previousStatus: 'DRAFT',
        newStatus: 'SUBMITTED',
      },
      {
        id: 'log-42',
        timestamp: '2026-06-09T15:10:00Z',
        userId: 'user-hod-01',
        userName: 'Dr. Kennedy Musumba',
        userRole: 'HOD',
        action: 'HOD_APPROVE_REGISTRATION',
        details: 'Authorized Cycle 1 registration docket.',
        previousStatus: 'AWAITING_HOD_APPROVAL',
        newStatus: 'APPROVED',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-01',
    targetUserId: 'user-stu-01',
    title: 'Registration Approved & Cleared',
    message: 'Your CDACC Assessment Unit Registration UR-2026-000142 has been officially approved by the Head of Department. You may now download and print your official institutional form.',
    type: 'SUCCESS',
    read: false,
    createdAt: '2026-06-12T14:45:00Z',
    linkRegistrationId: 'reg-001',
  },
  {
    id: 'notif-02',
    targetRole: 'TRAINER',
    title: 'New Unit Verification Tasks',
    message: 'Mercy Nekesa (TSNP/DICT/2024/0519) submitted units requiring your electronic verification.',
    type: 'INFO',
    read: false,
    createdAt: '2026-06-14T08:15:00Z',
    linkRegistrationId: 'reg-002',
  },
  {
    id: 'notif-03',
    targetRole: 'HOD',
    title: 'Registration Ready for Final HOD Approval',
    message: 'Brian Kipruto (TSNP/CIT/2025/0114) has all units successfully verified by assigned trainers. Ready for departmental approval stamp.',
    type: 'WARNING',
    read: false,
    createdAt: '2026-06-13T16:20:00Z',
    linkRegistrationId: 'reg-003',
  },
  {
    id: 'notif-admin-01',
    targetRole: 'ADMIN',
    title: 'Trainee Submission: Pending Trainer Verification',
    message:
      'Brenda kavere musoga (L5ICT/13903/24M) submitted 2 unit(s) for Cycle 1. Pending verification by: Douglas Omutanyi (2 units: IT/OS/ICT/CR/1/5, IT/OS/ICT/CR/4/5).',
    type: 'INFO',
    read: false,
    createdAt: '2026-09-04T05:30:00Z',
    linkRegistrationId: 'reg-d0x868rcq',
  },
];
